name: Deploy LMS Frontend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: deploy-lms-frontend
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PORT: ${{ secrets.SSH_PORT || '22' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare SSH key
        run: |
          echo "${{ secrets.SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Ensure target dirs on server
        run: |
          ssh -i key.pem -p "$SSH_PORT" -o StrictHostKeyChecking=no \
            "$SSH_USER@$SSH_HOST" 'mkdir -p /var/www/lms-frontend /var/www/lms-frontend/dist'

      - name: Upload sources (no src/)
        run: |
          rsync -az --delete \
            --exclude ".git" --exclude ".github" --exclude "node_modules" \
            -e "ssh -i key.pem -p $SSH_PORT -o StrictHostKeyChecking=no" \
            ./ "$SSH_USER@$SSH_HOST:/var/www/lms-frontend/"

      - name: Build on server & publish to /dist
        run: |
          ssh -i key.pem -p "$SSH_PORT" -o StrictHostKeyChecking=no \
            "$SSH_USER@$SSH_HOST" '
              set -e
              cd /var/www/lms-frontend
              npm ci
              npm run build
              rsync -az --delete dist/ /var/www/lms-frontend/dist/
            '
